In [4]:
import torch
print(torch.__version__)

2.11.0+cpu


In [5]:
import numpy as np
x = np.array([1,2,3])

In [7]:
import tensorflow as tf
x = torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


In [8]:
y = torch.tensor([
    [1,2],
    [3,4]
])

print(y.shape)

torch.Size([2, 2])


In [9]:
a = torch.tensor([1,2,3])

b = torch.tensor([4,5,6])

print(a+b)

print(a*b)

print(torch.dot(a,b))

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor(32)


In [10]:
x = torch.tensor(
    2.0,
    requires_grad=True
)

In [11]:
y = x**2

In [12]:
y.backward()

In [13]:
print(x.grad)

tensor(4.)


In [14]:
print(y)

tensor(4., grad_fn=<PowBackward0>)


In [15]:
layer = torch.nn.Linear(2,1)

print(layer.weight)

print(layer.bias)

Parameter containing:
tensor([[0.6051, 0.6464]], requires_grad=True)
Parameter containing:
tensor([0.1362], requires_grad=True)


In [16]:
x = torch.tensor([[2.0,3.0]])

output = layer(x)

print(output)

tensor([[3.2855]], grad_fn=<AddmmBackward0>)


In [17]:
relu = torch.nn.ReLU()

print(relu(output))

tensor([[3.2855]], grad_fn=<ReluBackward0>)


In [18]:
optimizer = torch.optim.SGD(
    layer.parameters(),
    lr=0.01
)

In [ ]:
for epoch in range(epochs):

    prediction = model(X)

    loss = criterion(prediction,y)

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim

# 1. Create fake data following the secret rule: Output = (2 * X1) + (3 * X2) + 5
# We create 100 rows of data, each with 2 input numbers
X = torch.randn(100, 2)
y = (2 * X[:, 0:1]) + (3 * X[:, 1:2]) + 5

# 2. Define the Model (Your Linear Layer)
model = nn.Linear(2, 1)

# 3. Define the Loss Function (Criterion) and the Optimizer
criterion = nn.MSELoss()  # Mean Squared Error: Measures how far off the guesses are
optimizer = optim.SGD(model.parameters(), lr=0.1) # Stochastic Gradient Descent with learning rate

# 4. Check the random weights BEFORE training
print("--- BEFORE TRAINING ---")
print("Weights:", model.weight.data)
print("Bias:", model.bias.data)
print("\nTraining the model now...\n")

# 5. The Training Loop (100 Epochs)
epochs = 100
for epoch in range(epochs):
    # Step 1: Make a guess
    prediction = model(X)

    # Step 2: Check the answer key (Calculate loss)
    loss = criterion(prediction, y)

    # Step 3: Erase old notes
    optimizer.zero_grad()

    # Step 4: Find out who to blame (Backward pass)
    loss.backward()

    # Step 5: Fix the mistakes (Update weights)
    optimizer.step()

    # Print progress every 20 rounds
    if (epoch + 1) % 20 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

# 6. Check the learned weights AFTER training
print("\n--- AFTER TRAINING ---")
print("Weights (Target is [[2.0, 3.0]]):", model.weight.data)
print("Bias (Target is [5.0]):", model.bias.data)


--- BEFORE TRAINING ---
Weights: tensor([[-0.3638, -0.0892]])
Bias: tensor([5.2768e-05])

Training the model now...

Epoch [20/100], Loss: 0.0230
Epoch [40/100], Loss: 0.0000
Epoch [60/100], Loss: 0.0000
Epoch [80/100], Loss: 0.0000
Epoch [100/100], Loss: 0.0000

--- AFTER TRAINING ---
Weights (Target is [[2.0, 3.0]]): tensor([[2.0000, 3.0000]])
Bias (Target is [5.0]): tensor([5.0000])
